/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ketnoimssql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class DSHocVien extends javax.swing.JFrame {

    /**
     * Creates new form LTGiaoDien
     */
    static DefaultTableModel dtm;
    public DSHocVien() {
        initComponents();
        loadComboBox();
        layDSHocVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_DSSach = new javax.swing.JLabel();
        jLabel_ThongTin = new javax.swing.JLabel();
        jLabel_MaHV = new javax.swing.JLabel();
        jTextField_MaHV = new javax.swing.JTextField();
        jLabel_HoTen = new javax.swing.JLabel();
        jTextField_HoTen = new javax.swing.JTextField();
        jLabel_TuaSach = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_Tinh = new javax.swing.JLabel();
        jLabel_ChucNang = new javax.swing.JLabel();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jLabel_DanhSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Hocvien = new javax.swing.JTable();
        jLabel_TuaSach1 = new javax.swing.JLabel();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jComboBox_Tinh = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_DSSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_DSSach.setForeground(new java.awt.Color(0, 51, 255));
        jLabel_DSSach.setText("DANH SÁCH HỌC VIÊN");

        jLabel_ThongTin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ThongTin.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_ThongTin.setText("Thông tin");

        jLabel_MaHV.setText("Mã HV");

        jLabel_HoTen.setText("Họ tên");

        jLabel_TuaSach.setText("Email");

        jLabel_Tinh.setText("Tỉnh");

        jLabel_ChucNang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ChucNang.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_ChucNang.setText("Chức năng");

        jButton_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Xoa.setForeground(new java.awt.Color(0, 51, 153));
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Thoat.setForeground(new java.awt.Color(0, 51, 153));
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        jButton_Luu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(0, 51, 153));
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jLabel_DanhSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DanhSach.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_DanhSach.setText("Danh sách");

        jTable_Hocvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HỌC VIÊN", "HỌ TÊN", "GIỚI TÍNH", "TỈNH", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Hocvien);

        jLabel_TuaSach1.setText("Giới tính");

        buttonGroup1.add(jRadioButton_Nam);
        jRadioButton_Nam.setText("Nam");

        buttonGroup1.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");

        jComboBox_Tinh.setEditable(true);
        jComboBox_Tinh.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ThongTin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_DanhSach)
                    .addComponent(jLabel_ChucNang)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton_Luu)
                        .addGap(54, 54, 54)
                        .addComponent(jButton_Xoa)
                        .addGap(58, 58, 58)
                        .addComponent(jButton_Thoat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_TuaSach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_MaHV)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_HoTen)
                                .addGap(0, 54, Short.MAX_VALUE))
                            .addComponent(jLabel_Tinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TuaSach1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jRadioButton_Nam)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_Nu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel_DSSach)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_DSSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MaHV)
                            .addComponent(jTextField_MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TuaSach)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_HoTen)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Tinh)
                            .addComponent(jComboBox_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TuaSach1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_Nam)
                        .addComponent(jRadioButton_Nu)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_ChucNang)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Thoat)
                    .addComponent(jButton_Luu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DanhSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void layDSHocVien()
    {
        try
        {
//            dtm = (DefaultTableModel) jTable_Hocvien.getModel();
//            dtm.setNumRows(0);
            dtm = (DefaultTableModel) jTable_Hocvien.getModel();
            dtm.setNumRows(0);
//            String query="select "
            String query = "SELECT mahv, hoten, phai, tentinh, email FROM hocvien, tinh WHERE tinh.matinh = hocvien.matinh";
            
            Connection ketNoi = KetNoiMSSQL.layKetNoi();
            Statement sta = ketNoi.createStatement();
            ResultSet ketQua = sta.executeQuery(query);
            
            while(ketQua.next())
            {
                Vector<Object> data = new Vector<>();
                data.add(ketQua.getString(1));
                data.add(ketQua.getString(2));
                data.add(ketQua.getString(3));
                data.add(ketQua.getString(4));
                data.add(ketQua.getString(5));
                dtm.addRow(data);
            }
        }
        catch(Exception ex)
        {
//            ex.printStackTrace();
                JOptionPane.showConfirmDialog(null, ex, "Khong the them vao table!", WIDTH);
        }
    }
    
    private void themHocVien(String maHV, String hoTen, String gioiTinh, String email, int tinh) {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "insert into dbo.HOCVIEN values (?,?,?,?,?)";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, maHV);
            ps.setString(2, hoTen);
            ps.setString(3, gioiTinh);
            ps.setInt(4, tinh);
            ps.setString(5, email);
            ps.executeUpdate();
        }
        catch(Exception ex)
        {
//            ex.printStackTrace();
               JOptionPane.showConfirmDialog(null, ex, "Khong tim thay table nay trong DB!", WIDTH);     
        }
    }
    
    public void loadComboBox()
    {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String query = "SELECT TENTINH FROM dbo.TINH";
        try
        {
            Statement sta = ketNoi.createStatement();
            ResultSet ketQua = sta.executeQuery(query);
            while(ketQua.next())
            {
                jComboBox_Tinh.addItem(ketQua.getString("TENTINH"));
            }
        }
        catch(Exception ex)
        {
//            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex, "Loi roi cha oi!", 1);
        }
    }
    
    private boolean kiemTraHV(String maHV){
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        boolean tontai = false;
        String sql = "select * from HOCVIEN where MAHV='" +maHV+ "'";
        try{
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                tontai = true;
            }
            rs.close();
            ps.close();
            ketNoi.close();
        }catch(Exception e){
            Logger.getLogger(DSHocVien.class.getName()).log(Level.SEVERE, null, e);
        }
        return tontai;
    }
    
    private void xoaHocVien(String maHV){
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "delete from HOCVIEN where MAHV = ?";
        try{
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, maHV);
            ps.executeUpdate();
        }catch(SQLException e){
            Logger.getLogger(DSHocVien.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed

        String maHV = jTextField_MaHV.getText();
        boolean check;
        int kiemtraMaHV=0;
        if(maHV.equals("")){ //0.Đã nhập mã HV; 1. Chưa nhập
            kiemtraMaHV = 1;
            JOptionPane.showMessageDialog(this, "Hay nhap Ma Hoc Vien ban muon xoa!");
        }else if(kiemtraMaHV!=1){
            check = kiemTraHV(maHV);
            if(check==true){
                int ret=JOptionPane.showConfirmDialog(this, "Ban chac chan muon xoa?", "Xac nhan", 0);
                if(ret==JOptionPane.CANCEL_OPTION){
                    return;
                }else if(ret==JOptionPane.OK_OPTION){
                    xoaHocVien(maHV);
                    JOptionPane.showMessageDialog(this, "Xoa Hoc Vien thanh cong.");
                    this.layDSHocVien();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Khong the xoa! Chua co thong tin hoc vien nay trong he thong.");
            }
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        //System.exit(0); //Đóng form.
        this.dispose();
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        try {
            Connection ketNoi = KetNoiMSSQL.layKetNoi();
            String sql = "SELECT matinh FROM tinh WHERE tentinh= ?";
            int tinh = 0;
            PreparedStatement ps;
            ps = ketNoi.prepareStatement(sql);
            ps.setString(1, jComboBox_Tinh.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            if(rs.next()) {tinh = rs.getInt("matinh");}
            
            String maHV = jTextField_MaHV.getText();
            String hoTen = jTextField_HoTen.getText();
            String gioiTinh = jRadioButton_Nam.isSelected() == true ? "Nam" : "Nữ";
            String email = jTextField_Email.getText();
                
//==================== Lưu ko kiểm tra ====================
            themHocVien(maHV, hoTen, gioiTinh, email,tinh);
            JOptionPane.showMessageDialog(this, "Thêm học viên thành công");
            layDSHocVien();
            jTextField_MaHV.setText("");
            jTextField_HoTen.setText("");
            jTextField_Email.setText("");
//=========================================================
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(DSHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSHocVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_Tinh;
    private javax.swing.JLabel jLabel_ChucNang;
    private javax.swing.JLabel jLabel_DSSach;
    private javax.swing.JLabel jLabel_DanhSach;
    private javax.swing.JLabel jLabel_HoTen;
    private javax.swing.JLabel jLabel_MaHV;
    private javax.swing.JLabel jLabel_ThongTin;
    private javax.swing.JLabel jLabel_Tinh;
    private javax.swing.JLabel jLabel_TuaSach;
    private javax.swing.JLabel jLabel_TuaSach1;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Hocvien;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_HoTen;
    private javax.swing.JTextField jTextField_MaHV;
    // End of variables declaration//GEN-END:variables
}
